---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-rest-app-deployment
  namespace: retail-project-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-rest-app
  template:
    metadata:
      labels:
        app: simple-rest-app
    spec:
      containers:
        - name: simple-rest-app
          image: archipelagos/simple-rest-app:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: simple-rest-app-service
  namespace: retail-project-dev
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: tcp
  selector:
    app: simple-rest-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-rest-app-ingress
  namespace: retail-project-dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-rest-app-service
            port:
              number: 80
